spring.application.name=workos corporate
spring.datasource.url=jdbc:mysql://localhost:3306/workosdb
spring.datasource.username=root
spring.datasource.password=p@ssw0rd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.com.workos.corporate=DEBUG